# Generated by Django 3.2.8 on 2021-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20211207_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpickup',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='donationpickup',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
    ]
