# Generated by Django 3.2.8 on 2021-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20211207_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('active_projects', models.IntegerField()),
                ('mission', models.TextField()),
                ('url', models.URLField()),
                ('logo_url', models.URLField()),
            ],
        ),
    ]
